export const ADD_CATEGORY = 'ADD_CATEGORY'
export const RECIEVED_ADD_CATEGORY = 'RECIEVED_ADD_CATEGORY'
export const FAILURE_ADD_CATEGORY = 'FAILURE_ADD_CATEGORY'

export const GET_CATEGORY = 'GET_CATEGORY'
export const RECIEVED_GET_CATEGORY = 'RECIEVED_GET_CATEGORY'
export const FAILURE_GET_CATEGORY = 'FAILURE_GET_CATEGORY'

export const GET_CATEGORY_ATTR = 'GET_CATEGORY_ATTR'
export const RECIEVED_GET_CATEGORY_ATTR = 'RECIEVED_GET_CATEGORY_ATTR'
export const FAILURE_GET_CATEGORY_ATTR = 'FAILURE_GET_CATEGORY_ATTR'


export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const RECIEVED_EDIT_CATEGORY = 'RECIEVED_EDIT_CATEGORY'
export const FAILURE_EDIT_CATEGORY = 'FAILURE_EDIT_CATEGORY'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const RECIEVED_DELETE_CATEGORY = 'RECIEVED_DELETE_CATEGORY'
export const FAILURE_DELETE_CATEGORY = 'FAILURE_DELETE_CATEGORY'

export const ADD_ITEM = 'ADD_ITEM'
export const RECIEVED_ADD_ITEM = 'RECIEVED_ADD_ITEM'
export const FAILURE_ADD_ITEM = 'FAILURE_ADD_ITEM'

export const GET_ITEMS = 'GET_ITEMS'
export const RECIEVED_GET_ITEMS = 'RECIEVED_GET_ITEMS'
export const FAILURE_GET_ITEMS = 'FAILURE_GET_ITEMS'

export const EDIT_ITEM = 'EDIT_ITEM'
export const RECIEVED_EDIT_ITEM = 'RECIEVED_EDIT_ITEM'
export const FAILURE_EDIT_ITEM = 'FAILURE_EDIT_ITEM'

export const DELETE_ITEM = 'DELETE_ITEM'
export const RECIEVED_DELETE_ITEM = 'RECIEVED_DELETE_ITEM'
export const FAILURE_DELETE_ITEM = 'FAILURE_DELETE_ITEM'
